### ISSUE TITLE
DB comments

### ISSUE THREAD

**Issue by omllobet** [NBISweden/LEGA-ingestion#10]
Hi Fred,
Would it be possible for you to add comments on the columns or a general short description? For example I am not sure about the purpose of the reencryption column.

For the status, instead of creating a enum, I'd say that it may be better to use a new table with the status and the description. Also You'll probably want to know what kind of error happened (and not have to look at the error text if possible), if it is something that you can retry or the user has to be contacted for some reason. Also for keeping track of what is going on a "In progress" status may not be enough.

For the filehash I understand that is the md5 of the unencrypted one? You probably also want to have the md5 of the encrypted one. So you can check the md5 of the file that you received if necessary. Also, when a file is archived you have to know under which key it was archived. You now may have just one key, but that could change so it is better to have a field that says which is the key used.

About the filename, my understanding is that is the one in the archive and that it is the file fullpath, but you may also want to keep the original name that was submitted to you. This is in the sense that if in this table you want to track files from the inbox to staging to the archive you probably don't want to lose information in each stage; because if you want to rollback or have any problem, it could be more difficult. You may need to track which files are on the inbox, because at the end you'll need to delete them, and it is better to have the original path than to having to reconstruct the name based on the current filename and status.

Another thing that is missing is the filesize. I think it is important to have it on the database.

Another thing that you could add is the file extension and a file extension version. That is the file extension of the file and how it was deduced (for example from the filename, or using a tool on the file)

Also you may want to add the database user that was used to do the insert or update for auditing purposes.

Thanks
Oscar

**Comment by silverdaz** [comment]
Wow....that's a long one.
Thanks for the suggestions.
I'll take them into account and update the database.

**Comment by silverdaz** [comment]
* **comments:** Yes, definitely a good point. I have added some.
* **status and ENUM:** A new table is not really necessary. It's a matter of nicely documenting the error code.
About the errors, you are right, it is important to understand what happened.
We can then retry or mark the file/submission has failed, and notify either the user or the admin depending on the type of error.
We are currently thinking and discussing about how to proceed.
For the "in progress", it's a matter of granularity. In our case, I'm not sure that it is not enough (since I optimized the decryption/checksum/re-encryption as (almost) one step. It works or it doesn't)

* **filehash:** Correct, it is the one of the unencrypted file.
We really don't need the checksum of the encrypted file from the inbox. It's just used to check that we really received the file. Assume we'd have another magic way to guarantee file reception, we would then not need the checksum of the encrypted file. Therefore, not exactly relevant to keep it around, once it passes the first checksum comparison (and ends up in the staging area).

* Storing **which key** was used for the re-encryption: Ooohh, yes, good point!
We could have several keys in the future. We need to store the one used for each file.
Not sure how I'll do that though.

* The **filename** field is the original name. The one in the inbox.
The stable_id is the final name, given by Central EGA. 
We don't have any file extensions so far. Is that necessary?

* **filesize**: Elaborate why it is important, please.

* **database user:** Sure, I can store that in the submission table.
However, do we have several database user?

**Comment by silverdaz** [comment]
I know what you mean with a new error table. I have included that change in my latest commit.

**Comment by omllobet** [comment]
- **comments:** _Thanks, I'll take a look at them_

- **status and ENUM:** "For the "in progress", it's a matter of granularity. In our case, I'm not sure that it is not enough (since I optimized the decryption/checksum/re-encryption as (almost) one step. It works or it doesn't)" -> _But it can't fail because of different reasons, it could be helpful to know them._

- **filehash:** -> _But then if you ever want to check that a file is ok, you'll need to decrypt it and check the unencrypted md5._

- **Storing which key was used for the re-encryption:** Ooohh, yes, good catch!
We could have several keys in the future. We need to store the one used for each file.
Not sure how I'll do that though. -> _You can just have a foreign field and save the encryption information (like type of encryption, path, size of the key...) there._

- The filename field is the original name. The one in the inbox.
The stable_id is the final name, given by Central EGA.
We don't have any file extensions so far. Is that necessary? -> _If you want for example to use the fuse layer, you'll need to have the extension of the file, so if you have cip files and gpg you only decrypt the correct ones._

- **filesize:** Elaborate why it is important, please. ->_Basically it is helpful to have it if you ever have to make decisions about the file, for example for distribution or if you ever need some statistics._

- **database user**: ->_Probably not now, but I think it is a good practise anyhow._
